
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/VMS
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    logging:
      level:
        org.springframework.security: DEBUG


  application:
    security:
      jwt:
        secret-key: 9a2f8c4e6b0d71f3e8b925a45747f894a3d6bc70fa8d5e21a15a6d8c3b9a0e7c
        expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000
